### ISSUE TITLE
hivemind.p2p.p2p_daemon_bindings.utils.P2PDaemonError: Daemon failed to start in 15.0 seconds

### ISSUE THREAD

**Issue by Sunhx100** [gensyn-ai/rl-swarm#294]
>> Good luck in the swarm!
>> Post about rl-swarm on X/twitter! --> https://tinyurl.com/swarmtweet
>> And remember to star the repo on GitHub! --> https://github.com/gensyn-ai/rl-swarm
INFO:hivemind_exp.chain_utils:✅ Connected to Gensyn Testnet
INFO:hivemind_exp.runner.gensyn.testnet_grpo_runner:Retrieved initial peers from chain: ['/ip4/38.101.215.14/tcp/31111/p2p/QmQ2gEXoPJg6iMBSUFWGzAabS2VhnzuS782Y637hGjfsRJ', '/ip4/38.101.215.14/tcp/31222/p2p/QmWhiaLrx3HRZfgXc2i7KW5nMUNK7P9tRc71yFJdGEZKkC', '/ip4/38.101.215.14/tcp/31333/p2p/QmQa1SCfYTxx7RvU7qJJRo79Zm1RAwPpkeLueDVJuBBmFp']
May 16 20:05:00.339 [INFO] Checking that identity from `/Users/sunhaoxiang/gensyn/rl-swarm/swarm.pem` is not used by other peers
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sunhaoxiang/gensyn/rl-swarm/hivemind_exp/gsm8k/train_single_gpu.py", line 61, in <module>
    main()
  File "/Users/sunhaoxiang/gensyn/rl-swarm/hivemind_exp/gsm8k/train_single_gpu.py", line 53, in main
    runner.run(model_args, grpo_args, training_args, gsm8k_stage1_samples)
  File "/Users/sunhaoxiang/gensyn/rl-swarm/hivemind_exp/runner/gensyn/testnet_grpo_runner.py", line 61, in run
    super().run(
  File "/Users/sunhaoxiang/gensyn/rl-swarm/hivemind_exp/runner/grpo_runner.py", line 196, in run
    dht = self.setup_dht(grpo_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sunhaoxiang/gensyn/rl-swarm/hivemind_exp/runner/gensyn/testnet_grpo_runner.py", line 40, in setup_dht
    dht = super().setup_dht(grpo_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sunhaoxiang/gensyn/rl-swarm/hivemind_exp/runner/grpo_runner.py", line 147, in setup_dht
    dht = hivemind.DHT(start=True, startup_timeout=30, **self._dht_kwargs(grpo_args))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sunhaoxiang/gensyn/rl-swarm/.venv/lib/python3.11/site-packages/hivemind/dht/dht.py", line 87, in __init__
    self.run_in_background(await_ready=await_ready)
  File "/Users/sunhaoxiang/gensyn/rl-swarm/.venv/lib/python3.11/site-packages/hivemind/dht/dht.py", line 148, in run_in_background
    self.wait_until_ready(timeout)
  File "/Users/sunhaoxiang/gensyn/rl-swarm/.venv/lib/python3.11/site-packages/hivemind/dht/dht.py", line 151, in wait_until_ready
    self._ready.result(timeout=timeout)
  File "/Users/sunhaoxiang/gensyn/rl-swarm/.venv/lib/python3.11/site-packages/hivemind/utils/mpfuture.py", line 254, in result
    return super().result(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.12/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.12/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
@hivemind.p2p.p2p_daemon_bindings.utils.P2PDaemonError: Daemon failed to start in 15.0 seconds

**Comment by diogoortega** [comment]
Hi @Sunhx100,
This issue should be resolved now, can you please make sure you're running the latest version of `rl-swarm` and try re-running the node?
Let me know how it goes.

**Comment by Sunhx100** [comment]
> 嗨[@Sunhx100](https://github.com/Sunhx100)，这个问题现在应该已经解决了，请您确保您正在运行最新版本的`rl-swarm`并尝试重新运行节点吗？告诉我进展如何。

I started running it on May 8th. The latest version is still not working now.

**Comment by chintanweb3** [comment]
still not working

> Hi [@Sunhx100](https://github.com/Sunhx100), This issue should be resolved now, can you please make sure you're running the latest version of `rl-swarm` and try re-running the node? Let me know how it goes.

still not working

**Comment by wwfelh** [comment]
same problem

**Comment by asukahan** [comment]
run clash for windows on mac, TUN mode, solved my problem.
